[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dout
board_build.filesystem = littlefs
lib_deps =
    https://github.com/ZinggJM/GxEPD2.git
    bblanchon/ArduinoJson@^7.0.0
    tzapu/WiFiManager@^2.0.17
